name: Pipeline with Stages
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Stage
        run: echo "Building the project..."
      
      - name: Test Stage
        run: echo "Running tests..."

      - name: Deploy Stage
        run: echo "Deploying the project..."